# Generated by Django 3.0.8 on 2020-08-21 13:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200812_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_postcode',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_town_or_city',
            field=models.CharField(default='', max_length=40),
        ),
    ]
