# Generated by Django 3.0.8 on 2020-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200822_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_county',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_email',
            field=models.EmailField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_town_or_city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
