# Generated by Django 3.0.8 on 2020-08-10 13:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import memberships_payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0019_auto_20200810_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(default=memberships_payment.models.Subscription.create_subscription_number, editable=False, max_length=6)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(default='', max_length=40)),
                ('street_address1', models.CharField(default='', max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Membership')),
            ],
        ),
    ]
