# Generated by Django 3.0.8 on 2020-08-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
