# Generated by Django 3.0.8 on 2020-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0003_auto_20200810_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='membership',
        ),
    ]
