# Generated by Django 3.0.8 on 2020-08-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0019_auto_20200810_1319'),
        ('memberships_payment', '0004_remove_subscription_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='total',
            new_name='subscription_total',
        ),
        migrations.CreateModel(
            name='SubscriptionLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.Membership')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='memberships_payment.Subscription')),
            ],
        ),
    ]
