# Generated by Django 3.0.8 on 2020-08-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0005_auto_20200811_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionlineitems', to='memberships_payment.Subscription'),
        ),
    ]
