# Generated by Django 3.0.8 on 2020-08-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0006_auto_20200811_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionlineitem',
            old_name='lineitem_total',
            new_name='subscriptionlineitem_total',
        ),
    ]
