# Generated by Django 3.0.8 on 2020-08-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0007_auto_20200811_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
