# Generated by Django 3.0.8 on 2020-08-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0010_auto_20200812_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
