# Generated by Django 3.0.8 on 2020-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0011_auto_20200812_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
