# Generated by Django 3.0.8 on 2020-08-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0012_auto_20200812_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='dd_account_no',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='dd_sortcode',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
