# Generated by Django 3.0.8 on 2020-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0013_auto_20200812_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='original_membershipsbag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
