# Generated by Django 3.0.8 on 2020-08-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200821_1347'),
        ('memberships_payment', '0016_auto_20200821_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='profiles.UserProfile'),
            preserve_default=False,
        ),
    ]
