# Generated by Django 3.0.8 on 2020-08-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200821_1347'),
        ('memberships_payment', '0017_auto_20200821_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='profiles.UserProfile'),
        ),
    ]
