# Generated by Django 3.0.8 on 2020-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0018_auto_20200822_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='county',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='town_or_city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
