# Generated by Django 3.0.8 on 2020-08-29 14:56

from django.db import migrations, models
import memberships_payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships_payment', '0019_auto_20200822_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_number',
            field=models.CharField(default=memberships_payment.models.Subscription.create_subscription_number, editable=False, max_length=10),
        ),
    ]
