# Generated by Django 3.0.8 on 2020-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
