# Generated by Django 3.0.8 on 2020-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_usermembership_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(max_length=30),
        ),
    ]
