# Generated by Django 3.0.8 on 2020-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20200804_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='full_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(max_length=20),
        ),
    ]
