# Generated by Django 3.0.8 on 2020-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20200804_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='full_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
