# Generated by Django 3.0.8 on 2020-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_auto_20200804_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
