# Generated by Django 3.0.8 on 2020-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_membership_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
