# Generated by Django 3.0.8 on 2020-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0014_auto_20200808_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='stripe_subscription_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
