# Generated by Django 3.0.8 on 2020-08-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0015_usermembership_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='active',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='county',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='date',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='town_or_city',
        ),
    ]
