# Generated by Django 3.0.8 on 2020-08-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0018_auto_20200810_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermembership',
            options={},
        ),
    ]
