# Generated by Django 3.0.8 on 2020-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0019_auto_20200810_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
