# Generated by Django 3.0.8 on 2020-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_shoppingbag',
        ),
    ]
