# Generated by Django 3.0.8 on 2020-08-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200821_1347'),
        ('checkout', '0005_remove_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.UserProfile'),
            preserve_default=False,
        ),
    ]
