# Generated by Django 3.0.8 on 2020-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200712_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='article_number',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
