# Generated by Django 3.0.8 on 2020-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200719_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='master_category',
            field=models.CharField(blank=True, choices=[('AC', 'Accessories'), ('CL', 'Clothing'), ('FW', 'Footwear'), ('SA', 'On sale')], default='', max_length=2, null=True),
        ),
    ]
