# Generated by Django 3.0.8 on 2020-08-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200724_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='master_category',
        ),
    ]
